version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "github-actions"
    labels:
      - "github-actions"
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "docker"
    labels:
      - "docker"
      - "dependencies"
    open-pull-requests-limit: 100
