version: 0.0
os: linux
files:
 - source: ./gitlangRoutes
   destination: /home/ec2-user/gitlangRoutes
hooks:
  ApplicationStop:
   - location: stop.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: init.sh
     timeout: 300
     runas: root
