name: ${GITHUB_REF##*/}

on:
  create

jobs:
  beta-pr:
    name: Beta Branch PR
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DISPATCH_REPO }}
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.DISPATCH_REPO }}
        run: |
          BRANCH=${GITHUB_REF##*/}
          git config user.name "chiefmikey"
          git config user.email "wolfemikl@gmail.com"
          git merge --allow-unrelated-histories origin/main || true
          git checkout --ours .
          git add .
          git commit -am 'Merge ${BRANCH} with main'
          git push -fu origin ${BRANCH}
          gh pr create --title ${BRANCH} --body 'Beta branch' --base main --head ${BRANCH}
