name: Beta Compile

on:
  pull_request:

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DISPATCH_REPO }}
          fetch-depth: 0

      - name: Merge branches
        run: |
          echo $(gh pr list -s open --json)
          for pull_request in $(gh pr list -s open --json); do
            echo "Compiling ${pull_request}"
            git
          done

          done
          git pull
