name: Beta Build

on:
  pull_request:

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'beta')
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DISPATCH_REPO }}
        fetch-depth: 0

    - name: Webpack
      run: |
        npm install
        NODE_ENV=production NODE_OPTIONS=--loader=ts-node/esm webpack --mode production

    - name: Prune
      run : |
        prune() {
          echo "${1}";
          if
          [ "${1}" != "." ] &&
          [ "${1}" != ".." ] &&
          [ "${1}" != "./docs" ] &&
          [ "${1}" != "./beta" ] &&
          [ "${1}" != "./LICENSE" ] &&
          [ "${1}" != "./README.md" ]; then
            rm -rf ${1};
          fi
        }
        export -f prune
        find . -maxdepth 1 | while read file; do prune ${file}; done
        rm docs/index.html docs/404.html docs/CNAME
        mv beta/index.html beta/404.html beta/CNAME docs/
        mkdir .github .github/workflows
        mv beta/beta-compile.yml beta/beta-branch.yml .github/workflows/

    - name: Push to Beta
      run: |
        git init
        git config user.name "Mikl Wolfe"
        git config user.email "wolfemikl@gmail.com"
        git remote add origin https://github.com/chiefmikey/gitlang-beta.git
        git add docs
        git checkout -b beta-build
        git commit -am 'Update beta branch'
        git push -u origin HEAD:refs/heads/${{ github.head_ref }}
        echo "https://beta.gitlang.net"
