name: Build Beta

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'beta')
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DISPATCH_REPO }}

    - name: Webpack
      run: |
        npm install
        NODE_ENV=production NODE_OPTIONS=--loader=ts-node/esm webpack --mode production

    - name: Beta Files
      run : |
        rm -rf docs/index.html docs/404.html docs/CNAME .github README.md
        # mkdir .github .github/workflows
        # mv beta/workflows/beta-compile.yml beta/workflows/beta-pr.yml .github/workflows/
        mv beta/index.html beta/404.html beta/CNAME docs/
        mv beta/README.md .

    - name: Prune Files
      run : |
        prune() {
          echo "${1}";
          if
          [ "${1}" != "." ] &&
          [ "${1}" != ".." ] &&
          [ "${1}" != "./.git" ] &&
          [ "${1}" != "./docs" ] &&
          [ "${1}" != "./LICENSE" ] &&
          [ "${1}" != "./README.md" ]; then
            rm -rf ${1};
          fi
        }
        export -f prune
        find . -maxdepth 1 | while read file; do prune ${file}; done
        git config user.name "chiefmikey"
        git config user.email "wolfemikl@gmail.com"
        git add .
        BRANCH=${{ github.head_ref }}
        git commit -am "${BRANCH}"

    - name: Update README.md
      run : |
        BRANCH=${{ github.head_ref }}
        PR_NUMBER="${{ github.event.pull_request.number }}"
        PR_TITLE="${{ github.event.pull_request.title }}"
        CURRENT_DATE=$(TZ=":US/Mountain" date +%y/%m/%d_%H:%M:%S)
        echo -e "#### Pull Request:\n" >> README.md
        echo -e "### [${PR_TITLE}](https://github.com/chiefmikey/gitlang/pull/${PR_ID})\n" >> README.md
        echo -e "#### Branch:\n" >> README.md
        echo -e "### ${BRANCH}\n" >> README.md
        echo -e "#### Date:\n" >> README.md
        echo -e "### ${CURRENT_DATE%%_*}\n" >> README.md
        echo -e "#### Time (MT):\n" >> README.md
        echo -e "### ${CURRENT_DATE##*_}\n" >> README.md
        echo -e "</div>\n" >> README.md
        git add .
        git commit -am "Beta README.md"

    - name: Push Main
      run: |
        BRANCH=${{ github.head_ref }}
        PR_TITLE="${{ github.event.pull_request.title }}"
        CURRENT_DATE=$(TZ=":US/Mountain" date +%y-%m-%d_%H-%M-%S)
        git remote set-url --add --push origin https://github.com/chiefmikey/gitlang-beta.git
        git reset $(git commit-tree HEAD^{tree} -m "PR: ${PR_TITLE} | Branch: ${BRANCH} | Date: ${CURRENT_DATE%%_*} | Time: ${CURRENT_DATE##*_}")
        git push -fu origin HEAD:main
        echo "PR: ${PR_TITLE}"
        echo "Branch: ${BRANCH}"
        echo "Date: ${CURRENT_DATE%%_*}"
        echo "Time: ${CURRENT_DATE##*_}"
        echo "https://beta.gitlang.net"

    # - name: Push Branch
    #   run: |
    #     BRANCH=${{ github.head_ref }}
    #     git remote set-url --add --push origin https://github.com/chiefmikey/gitlang-beta.git
    #     git reset $(git commit-tree HEAD^{tree} -m 'Beta Branch')
    #     git push -fu origin HEAD:refs/heads/${BRANCH}
    #     echo "https://beta.gitlang.net"
