name: Build Beta

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'beta')
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DISPATCH_REPO }}

    - name: Webpack
      run: |
        npm install
        NODE_ENV=production NODE_OPTIONS=--loader=ts-node/esm webpack --mode production

    - name: Beta Files
      run : |
        rm -rf docs/index.html docs/404.html docs/CNAME .github
        mkdir .github .github/workflows
        mv beta/beta-compile.yml beta/beta-pr.yml .github/workflows/
        mv beta/index.html beta/404.html beta/CNAME docs/
        git add .
        git commit -am "Beta Files"

    - name: Push Beta
      run: |
        git config user.name "chiefmikey"
        git config user.email "wolfemikl@gmail.com"
        BRANCH=${{ github.head_ref }}
        git remote set-url --add --push origin https://github.com/chiefmikey/gitlang-beta.git
        git reset $(git commit-tree HEAD^{tree} -m 'Beta Branch')
        git push -fu origin HEAD:refs/heads/${BRANCH}
        echo "https://beta.gitlang.net"
