name: Client Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Webpack
      run: |
        npm install
        NODE_ENV=production NODE_OPTIONS=--loader=ts-node/esm webpack --mode production

    - name: Prune
      run : |
        prune() {
          echo "${1}";
          if
          [ "${1}" != "." ] &&
          [ "${1}" != ".." ] &&
          [ "${1}" != "./.git" ] &&
          [ "${1}" != "./docs" ] &&
          [ "${1}" != "./LICENSE" ] &&
          [ "${1}" != "./README.md" ]; then
            rm -rf ${1};
          fi
        }
        export -f prune
        find . -maxdepth 1 | while read file; do prune ${file}; done

    - name: Push
      run: |
        git config user.name "Mikl Wolfe"
        git config user.email "wolfe@mikl.com"
        git add docs
        git commit -am 'Update production build'
        git push -fu origin main:client
