name: Prune Beta

on:
  pull_request:
    types:
      - closed

jobs:
  prune:
    if: github.event.pull_request.merged == true
    name: Prune
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: List Merged
      run: |
        FORMAT="%(if:equals=[gone])%(upstream:track)%(then)%(refname:short)%(end)"
        echo "::set-output name=merged_branches::$(git branch --list --format ${FORMAT})"
        echo ${MERGED_BRANCHES}

    - name: Checkout Beta
      id: checkout-beta
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DISPATCH_REPO }}
        repository: chiefmikey/gitlang-beta
        fetch-depth: 0

    - name: Delete Merged
      env:
        MERGED_BRANCHES: ${{ steps.checkout-beta.outputs.merged_branches }}
      run: |
        BRANCH=${{ github.head_ref }}
        BRANCHES=$(git branch)
        echo test merged: ${MERGED_BRANCHES}
        echo test branch: ${BRANCH}
        echo test branches: ${BRANCHES}
        for branch in $(echo ${BRANCHES}); do
          if [ -z "${MERGED_BRANCHES##*${branch}*}" ] || [ -z "${BRANCH##*${branch}*}" ]; then
            echo "Delete ${branch}"
            git push origin --delete ${branch}
          fi
        done
