name: "Snyk: Node"
on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Snyk Scan
        uses: snyk/actions/node@0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=./snyk.sarif
      - name: test
        run: |
          echo "current dir"
          pwd
          ls -la
          echo "one up"
          cd ..
          pwd
          ls -la
          echo "root: /"
          cd /
          pwd
          ls -la
      - name: Upload Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./snyk.sarif
