name: Test Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Webpack
      run: |
        npm install
        NODE_ENV=production NODE_OPTIONS=--loader=ts-node/esm webpack --mode production

    - name: Prune
      run : |
        find . -type f -not -name 'docs,README.md,LICENCE' -delete

    - name: Subdomain
      run : |
        echo "beta.gitlang.net" > docs/CNAME

    - name: Push
      run: |
        git checkout -b test
        git checkout test
        git config --global user.email "wolfemikl@gmail.com"
        git config --global user.name "Mikl Wolfe"
        git add docs
        git commit -am 'Update production build'
        git push -f origin main:test
