
name: Create diagram
on:
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.8.2
        with:
          excluded_paths: "ignore,.github"
